version: '3'
services:
  app:
    build:
      context: ./
      target: ww-dev
      args:
          WWWGROUP: '${WWWGROUP}'
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
    ports:
        - '${APP_PORT:-80}:80'
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - proxy
      - laravel
    depends_on:
      - mysql
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${PF}.rule=PathPrefix(`/`)"
        - "traefik.http.routers.${PF}.entryPoints=web"
        - "traefik.http.routers.${PF}-ssl.rule=PathPrefix(`/`)"
        - "traefik.http.routers.${PF}-ssl.entryPoints=websecure"
        - "traefik.http.routers.${PF}-ssl.tls=true"
        - "traefik.http.routers.${PF}-ssl.tls.certresolver=myresolver"
        - "traefik.http.routers.${PF}-ssl.tls.domains[0].main=${DOMAIN}"
        - "traefik.http.routers.${PF}-ssl.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${PF}.rule=Host(`${DOMAIN}`)"

  mysql:
      image: 'mysql/mysql-server:8.0'
      environment:
        environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      ports:
        - 3906:3306
      volumes:
        - 'mysql8:/var/lib/mysql'
        - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
      networks:
        - laravel
networks:
    laravel:
        driver: bridge
    proxy:
        #driver: bridge
        external: true
volumes:
    mysql8:
        driver: local
